trigger:
- '*'

pool:
  vmImage: 'ubuntu-16.04'

container: grahamschock/composite_dev_env:latest

steps:

- script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    rustup default nightly
    cargo install xargo
    rustup component add rust-src
  displayName: "Install Rust"
- script: |
    ./cos init
  displayName: 'Initialize system'

- script: |
    ./cos build
  displayName: 'Build System'
- script: |
    ./cos compose composition_scripts/sched.toml test
  displayName: 'Display Kernel Tests'
