trigger:
- '*'

pool:
  vmImage: 'ubuntu-16.04'

container : grahamschock/composite_dev_env:latest

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
  - script: | 
      rustup default nightly
      cargo install xargo
      rustup component add rust-src 
    displayName: Add Rust Composite Dependencies
  - script: |
      ./cos init
    displayName: Initialize Composite
  - script: |
      ./cos build
    displayName: Build Composite
  - script: | 
      ./cos compose composition_scripts/kernel_test.toml test
    displayName: Compile Kernel Test
  - script: |
      echo "Running Tests... (60s)"
      timeout --preserve-status 60 ./cos run system_binaries/cos_build-test/cos.img > kernel_test.txt
      exit 0
    displayName: Run Kernel Tests 
  - script : |
      cat kernel_tests.txt
    displayName: Display Kernel Tests
  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'tools/kernel_parse.py'