[system]
description = "Simple system: ping pong!"
constructor = "booter"

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}]

[[components]]
name = "ping"
img  = "tests.unit_pingpong"
deps = [{srv = "pong", interface = "pong"},
        {srv = "booter", interface = "init"}]
baseaddr = "0x1600000"

[[components]]
name = "pong"
img  = "pong.pingpong"
deps = [{srv = "booter", interface = "init"}]
implements = [{interface = "pong"}]
