[system]
description = "Simple system: ping pong!"

[[components]]
name = "ping"
img = "tests.unit_pingpong"
deps = [{srv = "pong", interface = "pong"}]
baseaddr = "0x1600000"

[[components]]
name = "pong"
img = "pong.pingpong"
